name: Deploy to SERVER SFManagers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to ECS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_NAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/SFManagers || exit
            
            git pull || exit
            
            npm install --legacy-peer-deps || exit

            npm run build:prod || exit

            sudo systemctl restart sfmanager || exit
          EOF
