         
name: Deploy to test SERVER (SFManagers)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_NAME }}@${{ secrets.SERVER_IP }} << EOF
            cd /var/www/dev_SFManagers || exit
            
            git pull origin development || exit
            
            npm install --legacy-peer-deps || exit

            npm run build || exit

            sudo systemctl restart devsfmanager || exit
          EOF